module Countries
  def self.list
    [
      ['Select Country', ''],
      ['Afghanistan', 'Afghanistan'],
      ['Albania', 'Albania'],
      ['Algeria', 'Algeria'],
      ['Argentina', 'Argentina'],
      ['Australia', 'Australia'],
      ['Austria', 'Austria'],
      ['Bangladesh', 'Bangladesh'],
      ['Belgium', 'Belgium'],
      ['Brazil', 'Brazil'],
      ['Canada', 'Canada'],
      ['China', 'China'],
      ['Colombia', 'Colombia'],
      ['Denmark', 'Denmark'],
      ['Egypt', 'Egypt'],
      ['Finland', 'Finland'],
      ['France', 'France'],
      ['Germany', 'Germany'],
      ['Greece', 'Greece'],
      ['India', 'India'],
      ['Indonesia', 'Indonesia'],
      ['Iran', 'Iran'],
      ['Iraq', 'Iraq'],
      ['Ireland', 'Ireland'],
      ['Israel', 'Israel'],
      ['Italy', 'Italy'],
      ['Japan', 'Japan'],
      ['Kenya', 'Kenya'],
      ['Malaysia', 'Malaysia'],
      ['Mexico', 'Mexico'],
      ['Netherlands', 'Netherlands'],
      ['New Zealand', 'New Zealand'],
      ['Nigeria', 'Nigeria'],
      ['Norway', 'Norway'],
      ['Pakistan', 'Pakistan'],
      ['Philippines', 'Philippines'],
      ['Poland', 'Poland'],
      ['Portugal', 'Portugal'],
      ['Russia', 'Russia'],
      ['Saudi Arabia', 'Saudi Arabia'],
      ['Singapore', 'Singapore'],
      ['South Africa', 'South Africa'],
      ['South Korea', 'South Korea'],
      ['Spain', 'Spain'],
      ['Sweden', 'Sweden'],
      ['Switzerland', 'Switzerland'],
      ['Thailand', 'Thailand'],
      ['Turkey', 'Turkey'],
      ['Ukraine', 'Ukraine'],
      ['United Arab Emirates', 'United Arab Emirates'],
      ['United Kingdom', 'United Kingdom'],
      ['United States', 'United States'],
      ['Vietnam', 'Vietnam']
    ]
  end
end

